apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: nodejs-app
    environment: {{ .Values.deploymentColor }}
data:
  PORT: "3000"
  ENV_COLOR: "{{ .Values.deploymentColor }}"
  APP_VERSION: "{{ .Values.image.tag }}"
  NODE_ENV: "production"