apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.deploymentColor }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nodejs-app
      version: {{ .Values.deploymentColor }}
  template:
    metadata:
      labels:
        app: nodejs-app
        version: {{ .Values.deploymentColor }}
    spec:
      containers:
      - name: nodejs-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3000
        env:
        - name: ENV_COLOR
          value: "{{ .Values.deploymentColor }}"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10